- name: CHECK IF LB EXISTS 
  uri:
    url: "{{ f5xc_api }}/config/namespaces/{{ f5xc_namespace }}/http_loadbalancers/{{ f5xc_object_prefix }}-http"
    method: GET
    headers: 
      Content-Type: "application/json"
      Authorization: "APIToken {{ f5xc_token }}"
    status_code: 
      - 200
      - 404
    validate_certs: no
  register: f5xc_http_lb_check
  retries: 0
  until: ('status' in f5xc_http_lb_check and (f5xc_http_lb_check.status == 200 or f5xc_http_lb_check.status == 404 ))


- name: DEPLOY NEW HTTP ONLY LB 
  uri:
    url: "{{ f5xc_api }}/config/namespaces/{{ f5xc_namespace }}/http_loadbalancers"
    method: POST
    headers: 
      Content-Type: "application/json"
      Authorization: "APIToken {{ f5xc_token }}"
    body: "{{ lookup('template','./templates/f5xc_lb_start_with_http.tpl') | to_nice_json }}"
    force_basic_auth: no
    status_code: 
      - 200
      - 409
    body_format: json
    validate_certs: no
  register: f5xc_response
  retries: 0
  until: ('status' in f5xc_response and (f5xc_response.status == 200 or f5xc_response.status == 409 ))
  when: f5xc_http_lb_check.status == 404


# - name: ...OR, IF LB ALREADY EXISTS, UPDATE IT 
#   uri:
#     url: "{{ f5xc_api }}/config/namespaces/{{ f5xc_namespace }}/http_loadbalancers/{{ f5xc_object_prefix }}-http"
#     method: PUT
#     headers: 
#       Content-Type: "application/json"
#       Authorization: "APIToken {{ f5xc_token }}"
#     body: "{{ lookup('template','./templates/f5xc_lb_start_with_http.tpl') }}"
#     force_basic_auth: no
#     status_code: 
#       - 200
#     body_format: json
#     validate_certs: no
#   register: f5xc_response
#   retries: 0
#   until: ('status' in f5xc_response and (f5xc_response.status == 200 ))
#   when: f5xc_http_lb_check.status == 200


- name: PAUSE TO CHECK DNS RESOLVES AND HTTP WORKS
  pause:
    prompt: "Test the HTTP version of the app http://{{inventory_hostname}} - PRESS ENTER TO CONTINUE."
  when: debug is true